//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIRT3_ElectricCarsMod.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIRT3_ElectricCarsMod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6r4 MG Metro 6R4
        ///6rb MG Metro 6R4 RallyX (rallycross)
        ///20x Peugeot 207 T16 4x4 (rallycross)
        ///131 Fiat 131 Abarth
        ///207 Peugeot 207 S2000
        ///alp Renault Alpine A110 1600S
        ///aqb Audi Sport Quattro Rallye
        ///aqp Audi Quattro S1 Pikes Peak
        ///bmt BMW Z4 M Coupe Motorsport
        ///bow Bowler Nemesis
        ///c4r Citroen C4 WRC
        ///dmy Dummy
        ///ers Ford Escort RS Cosworth
        ///ffr Ford Fiesta RS WRC
        ///fgk Ford Fiesta Gymkhana 3
        ///for Ford Focus RS WRC
        ///fpp Ford Fiesta OMSE Hillclimb Special
        ///fra Ford Fiesta Open Class
        ///frx Ford Fiesta Rallycross [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CarListKeyValue {
            get {
                return ResourceManager.GetString("CarListKeyValue", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon dirt3 {
            get {
                object obj = ResourceManager.GetObject("dirt3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green176\blue80;\red0\green77\blue187;}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sl276\slmult1\qc\cf1\lang9\b\f0\fs56 Elektric Cars Mod for DiRT 3\fs40\par
        ///\pard\sa200\sl276\slmult1\cf0\b0\fs22\par
        ///This mod removes sounds of engine and exhaust of a cars and now cars tend to sound like \cf1\b\fs24 EV\cf0\b0\fs22 s (Electric Vehicles). \cf1\b\fs24 EV\cf0\b0\fs22 s are very quiet due to electr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DiRT3ElectricCarMod {
            get {
                return ResourceManager.GetString("DiRT3ElectricCarMod", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DiRT3LOGOFINAL {
            get {
                object obj = ResourceManager.GetObject("DiRT3LOGOFINAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap elektric {
            get {
                object obj = ResourceManager.GetObject("elektric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ElektricCarMod2 {
            get {
                object obj = ResourceManager.GetObject("ElektricCarMod2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightning {
            get {
                object obj = ResourceManager.GetObject("lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap restoreoriginal2 {
            get {
                object obj = ResourceManager.GetObject("restoreoriginal2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
